// regionAreas.js
const regionAreas = {
  Arusha: [
    "Arusha Mjini",
    "Karatu",
    "Longido",
    "Meru",
    "Monduli",
    "Ngorongoro",
  ],
  "Dar es Salaam": [
    "Dar es Salaam Mjini",
    "Kigamboni",
    "Kinondoni",
    "Temeke",
    "Ubungo",
  ],
  Dodoma: [
    "Dodoma Mjini",
    "Bahi",
    "Chamwino",
    "Chemba",
    "Kondoa",
    "Kongwa",
    "Mpwapwa",
  ],
  Geita: ["Bukombe", "Chato", "Geita Mjini", "Mbogwe", "Nyang'wale"],
  Iringa: ["Iringa Mjini", "Kilolo", "Mafinga", "Mufindi"],
  Kagera: [
    "Biharamulo",
    "Bukoba Mjini",
    "Karagwe",
    "Kyerwa",
    "Missenyi",
    "Muleba",
    "Ngara",
  ],
  Katavi: ["Mlele", "Mpanda", "Mpimbwe", "Nsimbo", "Tanganyika"],
  Kigoma: ["Buhigwe", "Kakonko", "Kasulu", "Kibondo", "Kigoma Mjini", "Uvinza"],
  Kilimanjaro: ["Hai", "Moshi Mjini", "Mwanga", "Rombo", "Same", "Siha"],
  Lindi: ["Kilwa", "Lindi Mjini", "Liwale", "Mtama", "Nachingwea", "Ruangwa"],
  Manyara: ["Babati", "Hanang'", "Kiteto", "Mbulu", "Simanjiro"],
  Mara: ["Bunda", "Butiama", "Musoma", "Rorya", "Serengeti", "Tarime"],
  Mbeya: ["Busokelo", "Chunya", "Kyela", "Mbarali", "Mbeya Mjini", "Rungwe"],
  Morogoro: [
    "Gairo",
    "Ifakara",
    "Kilosa",
    "Malinyi",
    "Mlimba",
    "Morogoro Mjini",
    "Mvomero",
    "Ulanga",
  ],
  Mtwara: [
    "Masasi",
    "Mtwara Mjini",
    "Nanyamba",
    "Nanyumbu",
    "Newala",
    "Tandahimba",
  ],
  Mwanza: [
    "Buchosa",
    "Ilemela",
    "Kwimba",
    "Magu",
    "Misungwi",
    "Mwanza Mjini",
    "Sengerema",
    "Ukerewe",
  ],
  Njombe: ["Ledewa", "Makambako", "Makete", "Njombe Mjini", "Wanging'ombe"],
  "Pemba Kaskazini": ["Micheweni", "Wete"],
  "Pemba Kusini": ["Chakechake", "Mkoani"],
  Pwani: [
    "Bagamoyo",
    "Chalinze",
    "Kibaha",
    "Kibiti",
    "KIsarawe",
    "Mafia",
    "Mkurunga",
    "Rufiji",
  ],
  Rukwa: ["Kalambo", "Nkasi", "Sumbawanga"],
  Ruvuma: ["Madaba", "Mbinga", "Namtumbo", "Nyasa", "Songea", "Tunduru"],
  Shinyanga: ["Kahama", "Kishapu", "Msalala", "Shinyanga Mjini", "Ushetu"],
  Simiyu: ["Bariadi", "Busega", "Itilima", "Maswa", "Meatu"],
  Singida: ["Ikungi", "Iramba", "Itigi", "Manyoni", "Mkalama", "Singida MJini"],
  Songwe: ["Ileje", "Mbozi", "Momba", "Songwe Mjini", "Tunduma"],
  Tabora: [
    "Igunga",
    "Kaliua",
    "Nzega",
    "Sikonge",
    "Tabora Mjini",
    "Urambo",
    "Uyui",
  ],
  Tanga: [
    "Bumbuli",
    "Handeni",
    "Kilindi",
    "Korogwe",
    "Lushoto",
    "Mkinga",
    "Muheza",
    "Pangani",
    "Tanga Mjini",
  ],
  "Zanzibar (Unguja Kusini)": ["Kati Mjini", "Kusini"],
  "Zanzibar (Unguja Kaskazini)": ["Kaskazini A", "Kaskazini B"],
  "Zanzibar (Unguja Mjini Magharibi)": ["Magharibi A", "Magharibi B", "Mjini"],
};

export default regionAreas;
